car_search/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'car_search'  # Define app namespace

urlpatterns = [
    path('', views.index, name='index'),     # Home page
    path('search/', views.search, name='search'),  # Search page
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)





car_search_project/urls.py
from django.contrib import admin
from django.urls import path, include  # Import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car_search.urls')),  # Include app URLs
]


car_search/models.py
from django.db import models

# Create your models here.

car_search/views.py
from django.shortcuts import render
from bs4 import BeautifulSoup
import requests


def index(request):
    return render(request, 'car_search/index.html')

def search(request):
    if request.method == 'POST':
        model = request.POST.get('model')
        year = request.POST.get('year')
        zipcode = request.POST.get('zipcode')
        distance = request.POST.get('distance')

        # Construct the URL with the year parameter
        website = f'https://www.cars.com/shopping/results/?stock_type=cpo&makes%5B%5D={model}&models%5B%5D=&list_price_max=&maximum_distance={distance}20&zip={zipcode}'
        if year:
            website += f'&year={year}'

        response = requests.get(website)
        soup = BeautifulSoup(response.content, 'html.parser')
        results = soup.find_all('div', {'class': 'vehicle-card'})

        cars = []
        for result in results:
            car = {}
            car['name'] = result.find('h2').get_text() if result.find('h2') else 'n/a'
            car['mileage'] = result.find('div', {'class': 'mileage'}).get_text() if result.find('div',
                                                                                                  {'class': 'mileage'}) else 'n/a'
            car['dealer_name'] = result.find('div', {'class': 'dealer-name'}).get_text().strip() if result.find('div',
                                                                                                                   {'class': 'dealer-name'}) else 'n/a'
            car['rating'] = result.find('span', {'class': 'sds-rating__count'}).get_text() if result.find('span',
                                                                                                           {'class': 'sds-rating__count'}) else 'n/a'
            car['review_count'] = result.find('span', {'class': 'sds-rating__link'}).get_text() if result.find(
                'span', {'class': 'sds-rating__link'}) else 'n/a'
            car['price'] = result.find('span', {'class': 'primary-price'}).get_text() if result.find('span',
                                                                                                       {'class': 'primary-price'}) else 'n/a'
            car['image'] = result.find('img')['data-src'] if result.find('img') and 'data-src' in result.find(
                'img').attrs else 'n/a'
            if car['image'] == 'n/a':
                car['image'] = result.find('img')['src'] if result.find('img') and 'src' in result.find(
                    'img').attrs else 'n/a'
            cars.append(car)

            print(car['name'])

        return render(request, 'car_search/results.html', {'cars': cars})

    return render(request, 'car_search/error.html', {'message': 'Invalid request method.'})

car_search/templates/car_search/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Error</h1>
    <p>{{ message }}</p>
</body>
</html>

car_search/templates/car_search/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.72.0">
  <title>Chicago cars</title>

  <link rel="canonical" href="https://v5.getbootstrap.com/docs/5.0/examples/album/">



  <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css" integrity="sha512-gRH0EcIcYBFkQTnbpO8k0WlsD20x5VzjhOA1Og8+ZUAhcMUCvd+APD35FJw3GzHAP3e+mP28YcDJxVr745loHw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
 <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }
    .hero{
      background: rgb(244,244,244);
      background: radial-gradient(circle, rgba(244,244,244,1) 10%, rgba(84,89,89,0.9037814955083596) 100%);}
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


</head>

content

<body>

  <header>
    <div class="collapse bg-info" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">About</h4>
            <p class="text-muted">Chicago Picture Cars has been a trusted provider of vehicles for the film and TV industry for over a decade. With our extensive network of dealers and dedication to customer satisfaction, we're committed to helping you find the ideal vehicles to bring your creative vision to life.</p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Contact</h4>
            <ul class="list-unstyled">
              <li><a href="#" class="text-white">Follow on Twitter  </a></li>
              <li><a href="#" class="text-white">Like on Facebook  </a></li>
              <li><a href="#" class="text-white">Email us </a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-info bg-light shadow-sm shadow-lg">
      <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
          <i class="fa fa-car mx-2" aria-hidden="true"></i>
          <strong>Car Engine</strong>
        </a>
        <button class=" btn btn-outline-primary" type="button" data-toggle="collapse" data-target="#navbarHeader"
          aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation"> <i class="fa fa-list p-1" aria-hidden="true"></i>
          <!-- <span class="navbar-toggler-icon"></span> -->
        </button>
      </div>
    </div>
  </header>

  <main>

    <section class=" hero text-center container-fluid">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-6 p-5">
          <h1 class="font-weight-bold"> Chicago Picture Cars' Search Engine</h1>
          <p class="lead font-weight-bold" style="color:purple;">At Chicago Picture Cars, we understand the importance of finding the perfect vehicle for your film and TV productions.</p>
          <p>
            <a href="#" class="btn btn-primary my-2">Learn More</a>
            <a href="#" class="btn btn-secondary my-2">Get started</a>
          </p>
        </div>
        <div class="col-lg-6 col-md-6 mx-auto">
          <img src="{% static './car_search/images/sales.png' %}" alt="" width="75%">
        </div>
      </div>`


    </section>


<!--<section>-->
<!--  <div class="container text-center">-->
<!--    <div class="row">-->
<!--      <div class="col">-->
<!--      <div class="input-group mb-3 p-4">-->
<!--        <select class="form-select p-2" id="">-->
<!--          <option selected >Search by</option>-->
<!--          <option value="1">One</option>-->
<!--          <option value="2">Two</option>-->
<!--          <option value="3">Three</option>-->
<!--        </select>-->
<!--      </div> -->
<!--      </div>-->
<!--      <div class="col">-->
<!--        <div class=" margin-auto p-4">-->
<!--          <form class="d-flex">-->
<!--            <input class="form-control me-2 p-2" type="search" placeholder="Search" aria-label="Search">-->
<!--            <button class="btn btn-outline-info" type="submit"> <i class="fa fa-car" aria-hidden="true"></i>  </button>-->
<!--        </form>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</section>-->

<div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">

                      <div class="card bg-light shadow-lg">
                    <div class="card-body">
                        <h5 class="card-title">Select Car Make and Zipcode</h5>
                        <form action="{% url 'car_search:search' %}" method="POST">

                            {% csrf_token %}
                            <div class="input-group mb-3">
                              <div>
                                <input class="form-control" type="text" id="year" name="year" placeholder= "year">

                              </div>
                            <div class="form-group">
                                <select class="form-control" id="make" name="model">
                                    <option value="">All makes</option>
                                    <option value="acura">Acura</option>
                                    <option value="audi">Audi</option>
                                    <option value="bmw">BMW</option>
                                    <option value="buick">Buick</option>
                                    <option value="cadillac">Cadillac</option>
                                    <option value="chevrolet">Chevrolet</option>
                                    <option value="chrysler">Chrysler</option>
                                    <option value="dodge">Dodge</option>
                                    <option value="ford">Ford</option>
                                    <option value="genesis">Genesis</option>
                                    <option value="gmc">GMC</option>
                                    <option value="honda">Honda</option>
                                    <option value="hyundai">Hyundai</option>
                                    <option value="infiniti">INFINITI</option>
                                    <option value="jaguar">Jaguar</option>
                                    <option value="jeep">Jeep</option>
                                    <option value="kia">Kia</option>
                                    <option value="land_rover">Land Rover</option>
                                    <option value="lexus">Lexus</option>
                                    <option value="lincoln">Lincoln</option>
                                    <option value="mazda">Mazda</option>
                                    <option value="mercedes_benz">Mercedes-Benz</option>
                                    <option value="mini">MINI</option>
                                    <option value="mitsubishi">Mitsubishi</option>
                                    <option value="nissan">Nissan</option>
                                    <option value="porsche">Porsche</option>
                                    <option value="ram">RAM</option>
                                    <option value="subaru">Subaru</option>
                                    <option value="tesla">Tesla</option>
                                    <option value="toyota">Toyota</option>
                                    <option value="volkswagen">Volkswagen</option>
                                    <option value="volvo">Volvo</option>
                                </select>
                            </div>
                            <div class="form-group">
                              <select class="form-control" id="make" name="distance">
                                  <option value="">Distance</option>
                                  <option value="10">10  Miles</option>
                                  <option value="20">20 Miles</option>
                                  <option value="30">30 Miles</option>
                                  <option value="40">40 Miles</option>
                                  <option value="50">50 Miles</option>
                                  <option value="60">60 Miles</option>
                                  <option value="70">70 Miles</option>
                                  <option value="80">80 Miles</option>
                                  <option value="90">90 Miles</option>
                                  <option value="100">100 Miles</option>
                                  
                              </select>
                          </div>
                              <input type="text" class="form-control" placeholder="zipcode" name="zipcode">
                              <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
                            </div>
                            {% comment %} <button type="submit" class="btn btn-primary">Search</button> {% endcomment %}
                        </form>
                    </div>
                </div>

            </div>
        </div>
</div>
  </main>

  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-right mb-1">
        <a href="#"> <i class="fa fa-arrow-circle-up h2 text-secondary" aria-hidden="true"></i> </a>
      </p>
    </div>
  </footer>

</body>

</html>

car_search/templates/car_search/results.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">

  <title>Car Search Results</title>

  <link rel="canonical" href="https://v5.getbootstrap.com/docs/5.0/examples/album/">



  <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css" integrity="sha512-gRH0EcIcYBFkQTnbpO8k0WlsD20x5VzjhOA1Og8+ZUAhcMUCvd+APD35FJw3GzHAP3e+mP28YcDJxVr745loHw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
 <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }
    .hero{
      background: rgb(244,244,244);
      background: radial-gradient(circle, rgba(244,244,244,1) 10%, rgba(84,89,89,0.9037814955083596) 100%);}
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


</head>

<body>

  <header>
    <div class="collapse bg-info" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">About</h4>
            <p class="text-muted">Chicago Picture Cars has been a trusted provider of vehicles for the film and TV industry for over a decade. With our extensive network of dealers and dedication to customer satisfaction, we're committed to helping you find the ideal vehicles to bring your creative vision to life.</p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Contact</h4>
            <ul class="list-unstyled">
              <li><a href="#" class="text-white">Follow on Twitter  </a></li>
              <li><a href="#" class="text-white">Like on Facebook  </a></li>
              <li><a href="#" class="text-white">Email us </a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-info bg-light shadow-sm shadow-lg">
      <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
          <i class="fa fa-car mx-2" aria-hidden="true"></i>
          <strong>Car Engine</strong>
        </a>
        <button class=" btn btn-outline-primary" type="button" data-toggle="collapse" data-target="#navbarHeader"
          aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation"> <i class="fa fa-list p-1" aria-hidden="true"></i>
          <!-- <span class="navbar-toggler-icon"></span> -->
        </button>
      </div>
    </div>
  </header>

  <main>

    <section class=" hero text-center container-fluid">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-6 p-5">
          <h1 class="font-weight-bold"> Chicago Picture Cars' Search Engine</h1>
          <p class="lead font-weight-bold" style="color:purple;">At Chicago Picture Cars, we understand the importance of finding the perfect vehicle for your film and TV productions.</p>
          <p>
            <a href="#" class="btn btn-primary my-2">Learn More</a>
            <a href="#" class="btn btn-secondary my-2">Get started</a>
          </p>
        </div>
        <div class="col-lg-6 col-md-6 mx-auto">
          <img src="{% static './car_search/images/sales.png' %}" alt="" width="75%">
        </div>
      </div>`


    </section>


    <div class="container mt-5">
        <h1 class="mb-4">Search Results</h1>
        <div class="row">
            {% for car in cars %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{ car.image }}" class="card-img-top" alt="Car Image">
                    <div class="card-body">
                        <h5 class="card-title">{{ car.name }}</h5>
                        <p class="card-text">Mileage: {{ car.mileage }}</p>
                        <p class="card-text">Dealer: {{ car.dealer_name }}</p>
                        <p class="card-text">Rating: {{ car.rating }}</p>
                        <p class="card-text">Review Count: {{ car.review_count }}</p>
                        <p class="card-text">Price: {{ car.price }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    
    <p>{{ message }}</p>


  </main>

  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-right mb-1">
        <a href="#"> <i class="fa fa-arrow-circle-up h2 text-secondary" aria-hidden="true"></i> </a>
      </p>
    </div>
  </footer>

</body>

</html>